#!/bin/sh

python manage.py migrate
python manage.py collectstatic --no-input --clear

gunicorn weatherscraper.wsgi:application -b 0.0.0.0:8000 --workers 4 --max-requests 10 --timeout 20 --graceful-timeout 10
