# Generated by Django 4.2 on 2023-04-27 09:25

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=32, null=True)),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('Scheduled', 'Scheduled'), ('In_Progress', 'In_Progress'), ('Done', 'Done')], default='Scheduled', max_length=32, no_check_for_status=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=32, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
