# Generated by Django 4.2 on 2023-04-26 17:19

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[('Scheduled', 'Scheduled'), ('In_Progress', 'In_Progress'), ('Done', 'Done')], default='Scheduled', max_length=32, no_check_for_status=True, null=True),
        ),
    ]
